version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
- package-ecosystem: maven
  directory: "/camera-framework"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
- package-ecosystem: maven
  directory: "/camera-binding"
  schedule:
    interval: monthly
  open-pull-requests-limit: 15
