/*
 * MIT License
 *
 * Copyright (c) 2018-2020 Yoann CAPLAIN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.blackdread.camerabinding.jna;

import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk-header\EDSDKTypes.h:1395</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 * @since edsdk 13.11.10
 */
public class EdsCameraPos extends Structure {
	/** C type : EdsInt32 */
	public NativeLong status;
	/** C type : EdsInt32 */
	public NativeLong position;
	/** C type : EdsInt32 */
	public NativeLong rolling;
	/** C type : EdsInt32 */
	public NativeLong pitching;
	public EdsCameraPos() {
		super();
	}
    @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("status", "position", "rolling", "pitching");
	}
	/**
	 * @param status C type : EdsInt32<br>
	 * @param position C type : EdsInt32<br>
	 * @param rolling C type : EdsInt32<br>
	 * @param pitching C type : EdsInt32
	 */
	public EdsCameraPos(NativeLong status, NativeLong position, NativeLong rolling, NativeLong pitching) {
		super();
		this.status = status;
		this.position = position;
		this.rolling = rolling;
		this.pitching = pitching;
	}
	public EdsCameraPos(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EdsCameraPos implements Structure.ByReference {

	}
	public static class ByValue extends EdsCameraPos implements Structure.ByValue {

	}
}
