/*
 * MIT License
 *
 * Copyright (c) 2018-2020 Yoann CAPLAIN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.blackdread.camerabinding.jna;

import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk-header\EDSDKTypes.h:1407</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 * @since edsdk 13.14.0
 */
public class EdsFocusShiftSet extends Structure {
	/** C type : EdsInt32 */
	public NativeLong version;
	/** C type : EdsInt32 */
	public NativeLong focusShiftFunction;
	/** C type : EdsInt32 */
	public NativeLong shootingNumber;
	/** C type : EdsInt32 */
	public NativeLong stepWidth;
	/** C type : EdsInt32 */
	public NativeLong exposureSmoothing;
	public EdsFocusShiftSet() {
		super();
	}
    @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("version", "focusShiftFunction", "shootingNumber", "stepWidth", "exposureSmoothing");
	}
	/**
	 * @param version C type : EdsInt32<br>
	 * @param focusShiftFunction C type : EdsInt32<br>
	 * @param shootingNumber C type : EdsInt32<br>
	 * @param stepWidth C type : EdsInt32<br>
	 * @param exposureSmoothing C type : EdsInt32
	 */
	public EdsFocusShiftSet(NativeLong version, NativeLong focusShiftFunction, NativeLong shootingNumber, NativeLong stepWidth, NativeLong exposureSmoothing) {
		super();
		this.version = version;
		this.focusShiftFunction = focusShiftFunction;
		this.shootingNumber = shootingNumber;
		this.stepWidth = stepWidth;
		this.exposureSmoothing = exposureSmoothing;
	}
	public EdsFocusShiftSet(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EdsFocusShiftSet implements Structure.ByReference {

	}
	public static class ByValue extends EdsFocusShiftSet implements Structure.ByValue {

	}
}
