/*
 * MIT License
 *
 * Copyright (c) 2018-2020 Yoann CAPLAIN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
package org.blackdread.camerabinding.jna;

import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;

import java.util.Arrays;
import java.util.List;

/**
 * <i>native declaration : sdk-header\EDSDKTypes.h:1420</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 * @since edsdk 13.11.10
 */
public class EdsManualWBData extends Structure {
	/** C type : EdsInt32 */
	public NativeLong valid;
	/** C type : EdsInt32 */
	public NativeLong dataSize;
	/** C type : EdsChar[32] */
	public byte[] szCaption = new byte[32];
	/** C type : EdsInt8[8] */
	public byte[] data = new byte[8];
	public EdsManualWBData() {
		super();
	}
    @Override
	protected List<String> getFieldOrder() {
		return Arrays.asList("valid", "dataSize", "szCaption", "data");
	}
	/**
	 * @param valid C type : EdsInt32<br>
	 * @param dataSize C type : EdsInt32<br>
	 * @param szCaption C type : EdsChar[32]<br>
	 * @param data C type : EdsInt8[8]
	 */
	public EdsManualWBData(NativeLong valid, NativeLong dataSize, byte szCaption[], byte data[]) {
		super();
		this.valid = valid;
		this.dataSize = dataSize;
		if ((szCaption.length != this.szCaption.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.szCaption = szCaption;
		if ((data.length != this.data.length))
			throw new IllegalArgumentException("Wrong array size !");
		this.data = data;
	}
	public EdsManualWBData(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends EdsManualWBData implements Structure.ByReference {

	}
	public static class ByValue extends EdsManualWBData implements Structure.ByValue {

	}
}
