package org.blackdread.camerabinding.jna;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk-header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagEdsFocusShiftSet extends Structure {
	/** C type : EdsInt32 */
	public NativeLong version;
	/** C type : EdsInt32 */
	public NativeLong focusShiftFunction;
	/** C type : EdsInt32 */
	public NativeLong shootingNumber;
	/** C type : EdsInt32 */
	public NativeLong stepWidth;
	/** C type : EdsInt32 */
	public NativeLong exposureSmoothing;
	public tagEdsFocusShiftSet() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("version", "focusShiftFunction", "shootingNumber", "stepWidth", "exposureSmoothing");
	}
	/**
	 * @param version C type : EdsInt32<br>
	 * @param focusShiftFunction C type : EdsInt32<br>
	 * @param shootingNumber C type : EdsInt32<br>
	 * @param stepWidth C type : EdsInt32<br>
	 * @param exposureSmoothing C type : EdsInt32
	 */
	public tagEdsFocusShiftSet(NativeLong version, NativeLong focusShiftFunction, NativeLong shootingNumber, NativeLong stepWidth, NativeLong exposureSmoothing) {
		super();
		this.version = version;
		this.focusShiftFunction = focusShiftFunction;
		this.shootingNumber = shootingNumber;
		this.stepWidth = stepWidth;
		this.exposureSmoothing = exposureSmoothing;
	}
	public tagEdsFocusShiftSet(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagEdsFocusShiftSet implements Structure.ByReference {
		
	};
	public static class ByValue extends tagEdsFocusShiftSet implements Structure.ByValue {
		
	};
}
