package org.blackdread.camerabinding.jna;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk-header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagEdsRect extends Structure {
	/** C type : EdsPoint */
	public tagEdsPoint point;
	/** C type : EdsSize */
	public tagEdsSize size;
	public tagEdsRect() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("point", "size");
	}
	/**
	 * @param point C type : EdsPoint<br>
	 * @param size C type : EdsSize
	 */
	public tagEdsRect(tagEdsPoint point, tagEdsSize size) {
		super();
		this.point = point;
		this.size = size;
	}
	public tagEdsRect(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagEdsRect implements Structure.ByReference {
		
	};
	public static class ByValue extends tagEdsRect implements Structure.ByValue {
		
	};
}
