package org.blackdread.camerabinding.jna;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : sdk-header\EDSDKTypes.h</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class tagEdsCameraPos extends Structure {
	/** C type : EdsInt32 */
	public NativeLong status;
	/** C type : EdsInt32 */
	public NativeLong position;
	/** C type : EdsInt32 */
	public NativeLong rolling;
	/** C type : EdsInt32 */
	public NativeLong pitching;
	public tagEdsCameraPos() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("status", "position", "rolling", "pitching");
	}
	/**
	 * @param status C type : EdsInt32<br>
	 * @param position C type : EdsInt32<br>
	 * @param rolling C type : EdsInt32<br>
	 * @param pitching C type : EdsInt32
	 */
	public tagEdsCameraPos(NativeLong status, NativeLong position, NativeLong rolling, NativeLong pitching) {
		super();
		this.status = status;
		this.position = position;
		this.rolling = rolling;
		this.pitching = pitching;
	}
	public tagEdsCameraPos(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends tagEdsCameraPos implements Structure.ByReference {
		
	};
	public static class ByValue extends tagEdsCameraPos implements Structure.ByValue {
		
	};
}
